apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: sparkify-star-schema
  namespace: spark-apps
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "dutradocker/spark-py:3.2.0"
  imagePullPolicy: Always
  mainApplicationFile: s3a://dutrajardim-etls/sparkify_etls/sparkify_script.py
  arguments:
  - "olap_job"
  sparkVersion: "3.2.0"
  deps:
    pyFiles:
    - https://minio.minio-tenant/dutrajardim-etls/sparkify_etls/sparkify_etls-0.1.0-py3.9.egg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=admin%2F20220102%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220102T193551Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=bfe08c6dc6dff2a48f1be999a6ffa25b02119b1d144967134cff572a41bd894f
  sparkConf:
    spark.eventLog.enabled: "true"
    spark.eventLog.dir: "s3a://spark-logs/events" 
  hadoopConf:
    fs.s3a.aws.credentials.provider: "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    fs.s3a.path.style.access: "true"
    fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    fs.s3a.endpoint: "https://minio.minio-tenant.svc.cluster.local"
    fs.s3a.access.key: "admin"
    fs.s3a.secret.key: "6bd71ace-8866-407a-9bcc-714bc5753f18"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    serviceAccount: spark
    javaOptions: "-Divy.cache.dir=/tmp -Divy.home=/tmp"
    cores: 1
    memory: "4g"
    labels:
      version: 3.2.0
  executor:
    serviceAccount: spark
    javaOptions: "-Divy.cache.dir=/tmp -Divy.home=/tmp"
    cores: 1
    instances: 2
    memory: "4g"
    labels:
      version: 3.2.0
