import React from 'react'
import Layout from '../components/layout'
import FilesNav from '../components/filesNav'

export default function PythonFiles() {
    return (
        <Layout>
            <div className="row">
                <div className="col-12 col-md-3 mb-5 order-md-2">
                    <FilesNav />
                </div>
                <div className="col-12 col-md-9 order-md-1">
                    <div className="row">
                        <div className="col">
                            <h2>Functions docstrings</h2>
                            <p>
                                Here you can read about each function created for the python modules.
                                The Gatsby Js extracts docstrings from each python file using a parser
                                generated by the <a target="_blank" href='https://www.antlr.org/'>ANTLR tool</a>,
                                and to help you browse through the documentation, I have organized it in the
                                same way the files are in the project.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </Layout>
    )
}